/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package st.jigasoft.xmlsql.view;

import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import st.jigasoft.xmldb.model.Type;
import st.jigasoft.xmldb.model.TypeTreat;
import st.jigasoft.xmlsql.references.RText;

/**
 *
 * @author xdata
 */
public class PanelTreater extends javax.swing.JPanel {
    private boolean openDetais;
    private CollumnView collumnView;
    private final DefaultComboBoxModel<Type> model;

    /**
     * Creates new form PanelTreater
     */
    public PanelTreater() {
        initComponents();
        this.openDetais = false;
        this.model = new DefaultComboBoxModel<>();
        
        this.comboTreatTypes.setModel(this.model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        xmlAtribute = new javax.swing.JLabel();
        panelDetais = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboTreatTypes = new javax.swing.JComboBox<Type>();
        jLabel4 = new javax.swing.JLabel();
        editDataBaseName = new st.jigasoft.dbutil.view.EditText();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("XML Attribute");

        xmlAtribute.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        xmlAtribute.setText(" ");

        jLabel2.setText(RText.CollumnType);

        comboTreatTypes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTreatTypesItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelDetaisLayout = new javax.swing.GroupLayout(panelDetais);
        panelDetais.setLayout(panelDetaisLayout);
        panelDetaisLayout.setHorizontalGroup(
            panelDetaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(comboTreatTypes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDetaisLayout.setVerticalGroup(
            panelDetaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetaisLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboTreatTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Data Base name");

        editDataBaseName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editDataBaseNameKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(panelDetais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(xmlAtribute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(editDataBaseName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(xmlAtribute))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editDataBaseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDetais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboTreatTypesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTreatTypesItemStateChanged
        onChangeType(evt);
    }//GEN-LAST:event_comboTreatTypesItemStateChanged

    private void editDataBaseNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editDataBaseNameKeyReleased
        keyRelecesd(evt);
    }//GEN-LAST:event_editDataBaseNameKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Type> comboTreatTypes;
    private st.jigasoft.dbutil.view.EditText editDataBaseName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelDetais;
    private javax.swing.JLabel xmlAtribute;
    // End of variables declaration//GEN-END:variables

    
    public void onTreatCollumn(CollumnView collumnView)
    {
        this.collumnView = collumnView;
        if(collumnView.getType() != null)
            this.comboTreatTypes.setSelectedItem(collumnView.getType());
        else this.comboTreatTypes.setSelectedIndex(0);
        this.xmlAtribute.setText(collumnView.getOriginalName());
        this.editDataBaseName.setText(this.collumnView.getDataBaseName());
        
    }

    private void onChangeType(ItemEvent evt) {
        if(collumnView != null)
        {
            this.collumnView.setType((TypeTreat) evt.getItem());
        }
    }

    private void keyRelecesd(KeyEvent evt) {
        if(collumnView != null)
        {
            this.collumnView.dataBaseText(this.editDataBaseName.getText());
        }
    }

    void addTypeTreater(TypeTreat treatText) {
        this.model.addElement(treatText);
    }

    TypeTreat getDefaultTreat() {
        return (TypeTreat) this.comboTreatTypes.getItemAt(0);
    }
}
